[package]
name = "kbignum_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "kbignum_ffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"
libc = "0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
